In [1]:
!pip install numpy

In [4]:
import numpy as np

In [24]:
import numpy as np
a = np.array([1,4,55,63,33,99,2], dtype= 'int32')
print(a)

[ 1  4 55 63 33 99  2]


In [11]:
a.ndim

1

In [21]:
a.shape

(7,)

In [25]:
a.dtype

dtype('int32')

In [26]:

b = np.array([[2, 33, 23, 11, 4, 7, 98],[21, 11, 76, 78, 67, 90, 100]])
print(b)

[[  2  33  23  11   4   7  98]
 [ 21  11  76  78  67  90 100]]


In [18]:
b.ndim

2

In [23]:
b.shape

(2, 7)

In [27]:
b.dtype

dtype('int32')

# Indexing In NumPy

In [30]:
Example=np.array([[22, 33, 44, 55],[66, 77, 88, 99]])
print(Example)

[[22 33 44 55]
 [66 77 88 99]]


In [31]:
Example[1,1]

77

In [34]:
Example[1,3]

99

In [35]:
Example[:,0]

array([22, 66])

In [36]:
Example[1,:]

array([66, 77, 88, 99])

In [131]:
Example1=np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
print(Example1)

[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]


In [39]:
Example1[0,1,]

array([4, 5])

In [41]:
Example1[0,0,0]

2

In [132]:
Example1[0,1,:]

array([4, 5])

# Instalizing different types of matrix:

In [2]:
import numpy as np

In [9]:
Example2=np.zeros(5)
print(Example2)

[0. 0. 0. 0. 0.]


In [16]:
Example3=np.zeros((3,10))
print(Example3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
Example4=np.ones(5)
print(Example4)

[1. 1. 1. 1. 1.]


In [17]:
Example5=np.ones((3,10))
print(Example5)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [119]:
Example6=np.ones(10)*99
aa=Example6.reshape(2,5)
print(aa)

[[99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99.]]


In [36]:
Example7=np.array([[2, 3, 4, 5],[6, 7, 8, 9]])
np.full_like(Example7, 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

# Random Decimal Numbers:

In [41]:
np.random.rand(4,2)

array([[0.26523152, 0.43966549],
       [0.71289877, 0.51730879],
       [0.57159302, 0.95583214],
       [0.10102065, 0.12383561]])

In [42]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.random.random_sample(a.shape)

array([[0.59637239, 0.22954172, 0.25417068],
       [0.10258764, 0.85550717, 0.54289387],
       [0.24377593, 0.51916956, 0.51269621]])

# Random Integer Value:

In [127]:

ab=np.random.randint(,size(3,3))
print(ab)

NameError: name 'size' is not defined

# Identity Matrix:

In [46]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Repeat an Array:

In [51]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Problem 1:

In [53]:
output= np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
z=np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [57]:
output[1:4, 1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [58]:
output[2,2]=9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Array copy:Case1

In [59]:
a=np.array([1,2,3])
b=a
b[0]=100
print(b)

[100   2   3]


# Array Copy:Case2

In [60]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)

[100   2   3]


# Mathematics:

In [63]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(b**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[16 25 36]


# Linear Algebra:

In [71]:
a=np.ones([2,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [82]:
b=np.full((3,4),6)
print(b)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [83]:
np.matmul(a,b)

array([[18., 18., 18., 18.],
       [18., 18., 18., 18.]])

# To find determinant:

In [84]:
c=np.identity(5)
np.linalg.det(c)

1.0

# Statistics:

In [87]:
Stats=np.array([[1,2,3],[4,5,6]])
print(Stats)

[[1 2 3]
 [4 5 6]]


In [88]:
np.min(Stats)

1

In [89]:
np.max(Stats)

6

In [90]:
np.min(Stats, axis=0)

array([1, 2, 3])

In [92]:
np.max(Stats, axis=0)

array([4, 5, 6])

In [93]:
np.min(Stats, axis=1)

array([1, 4])

In [91]:
np.max(Stats, axis=1)

array([3, 6])

# Reshape Arrays:

In [95]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [97]:
after=a.reshape((6,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Vertical stacking Matrix:

In [99]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

# Horizonal Stacking:

In [101]:
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2,h1,h2))

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0.]])

# Boolean masking & Advanced indexing:

In [103]:
filedata=np.array([1,2,3,33,56,90,28,78,89])
filedata>50

array([False, False, False, False,  True,  True, False,  True,  True])

In [108]:
filedata1=np.array([[1,13,21,196,6,3],[3,42,12,766,6,55],[1,22,33,999,40,1]])
np.array(filedata1>50, axis=0)

TypeError: array() got an unexpected keyword argument 'axis'

In [109]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [110]:
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [111]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [113]:
a[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])